# Generated by Django 5.1.5 on 2025-03-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productbase_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='PrimaryCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.primarycategory'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategory'),
        ),
    ]
