# Generated by Django 5.1.5 on 2025-03-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_pricingdetails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='formulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.formulation'),
        ),
    ]
