# Generated by Django 5.1.5 on 2025-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productbase_quantity_alter_productbase_formulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
