# Generated by Django 5.1.5 on 2025-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productbase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/`{product.brand_name}`'),
        ),
    ]
