# Generated by Django 5.1.5 on 2025-03-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productimage_image1_alter_productimage_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdetails',
            name='offer',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
