# Generated by Django 5.1.5 on 2025-03-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_pricingdetails_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
