# Generated by Django 5.1.5 on 2025-03-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_pricingdetails_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pid',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='PricingDetails',
            field=models.ForeignKey(db_column='pricing_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='store.pricingdetails'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productImage',
            field=models.ForeignKey(db_column='image_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='store.productimage'),
        ),
    ]
