# Generated by Django 5.1.5 on 2025-03-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_pid_cart_product_cart_pricingdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='PricingDetails',
            new_name='Pricing',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='productImage',
            new_name='prodImage',
        ),
    ]
