# Generated by Django 5.1.5 on 2025-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_pricingdetails_cart_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkedToProceed',
            field=models.BooleanField(default=True),
        ),
    ]
