# Generated by Django 5.1.5 on 2025-03-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
