# Generated by Django 5.1.5 on 2025-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_delete_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
    ]
