# Generated by Django 5.1.5 on 2025-04-02 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0021_order_address_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productimage')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.importantinfo')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pricingdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productbase')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
