# Generated by Django 5.1.5 on 2025-03-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 2 tablets', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice a day, Once daily', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('refill_reminder', models.BooleanField(default=True)),
                ('refill_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
