# Generated by Django 5.1.5 on 2025-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_familydoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydoctor',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
