# Generated by Django 5.1.5 on 2025-03-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_familydoctor_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyDoctor',
        ),
    ]
