# Generated by Django 5.1.5 on 2025-03-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_patientvital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientVital',
        ),
    ]
