# Generated by Django 5.1.5 on 2025-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_patientvital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvital',
            name='height',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
