# Generated by Django 5.1.5 on 2025-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('physician', 'Physician'), ('practitioner', 'Practitioner'), ('researcher', 'Researcher'), ('service_provider', 'Service Provider'), ('health_creator', 'Health Content Creator'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
