# Generated by Django 5.1.5 on 2025-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='houseNo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
