# Generated by Django 5.1.5 on 2025-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=6),
        ),
    ]
