# Generated by Django 5.1.5 on 2025-04-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
