# Generated by Django 5.1.5 on 2025-03-04 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongFormVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='videos/long/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/long/')),
                ('duration', models.DurationField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Entertainment', 'Entertainment'), ('News', 'News'), ('Sports', 'Sports'), ('Music', 'Music'), ('Gaming', 'Gaming'), ('Other', 'Other')], max_length=100)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='videos/shorts/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/shorts/')),
                ('duration', models.DurationField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
