# Generated by Django 5.1.5 on 2025-03-04 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_longformvideo_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longformvideo',
            name='file',
            field=models.FileField(upload_to='long_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'flv', 'wmv'])]),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='file',
            field=models.FileField(upload_to='short_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'flv', 'wmv'])]),
        ),
    ]
