# Generated by Django 5.1.5 on 2025-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_appointment_rescheduled_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
